### ISSUE TITLE
Current API Issues

### ISSUE THREAD

**Issue by OmniCypher-** [curz46/abilityapi#4]
One of the issues we need to address ASAP is the lack of communication between `Ability` and `Sequence`. Currently, there is no way to access the `Events`/`Actions` that caused them. For example, this is a big problem for abilities that want to immediately damage a target.

**Proposed solution:** We will catalog each event reference in a custom list (`EventList<T extends Event>` or something) and pass that along with the current `Player` reference into `createInstance()`.

This [Gist](https://gist.github.com/OmniCypher-/016d5d19a4ff0586edfed8a0975436ad) outlines the proposed changes to `Ability` and `AbilityProvider`, and a few features of `EventList`.

As of now, the current idea is to simply have a `get(<T extends Event>)` method which will return the first instance of the passed `Event` or `null`. In addition, we can also have overloaded `get(<T extends Event>, int)` method which will return each subsequent `Event` the `EventList` contains or `null`.

**Comment by curz46** [comment]
#7: addressed.
